name: CI - Build Backend e Frontend

on:
  push:
    branches: [ main, develop, DevelopRefactor]
  pull_request:
    branches: [ main, develop, DevelopRefactor ]

jobs:
  backend:
    name: Build Backend (Maven / Java 21)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BackEnd/Senai/Senai

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Dar permissão de execução ao Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar backend (mvn package)
        run: ./mvnw -B clean package -DskipTests

  frontend:
    name: Build Frontend (Angular / Node 20)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: FrontEnd/pi_2026_1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: FrontEnd/pi_2026_1/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Compilar frontend (ng build)
        run: npm run build
